#! /bin/sh
#
# Simple control script for a dashing dashboard 
# https://github.com/Shopify/dashing
#
# chkconfig: 345 20 80
# description: Dashing dashboard control script

DASHING_DIR=/opt/dashboard
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

case "$1" in
    start)
        echo "Dashing starting..."
        cd $DASHING_DIR; dashing start -d -p 80 -e production
        ;;
    stop)
        echo "Dashing stopping..."
        cd $DASHING_DIR; bundle exec thin stop
        ;;
    restart)
        echo "Dashing restarting..."
        cd $DASHING_DIR; bundle exec thin restart -p80 -e production
        ;;
    status)
        THIN_PID=$(lsof -i :80 | awk '{print $2}' | tail -n1)
        if [ "$THIN_PID" != "" ]; then
            echo "Dashing is running with pid $THIN_PID"
        else
            echo "Dashing is not running"
        fi

        ;;
    *)
        echo "Dashing"
        echo $"Usage: $0 {start|stop|restart|status}"
        exit 1
esac
exit 0
